### ISSUE TITLE
Change fontFamily ?

### ISSUE THREAD

**Issue by mehdijjz** [sportsbet/react-native-ultra-picker-ios#2]
how can I change items fontFamily ?

**Comment by timsawtell-sportsbet** [comment]
Changes to font family and font size will need an enhancement to the native module (and the RN component), perhaps the Group component can accept a string property for "fontFamily" and number for "fontSize"? (the setting would apply to all Items in that Group).
If you want you can submit a PR with this change, if you're unsure about how to make the change I can get around to it sometime soon.

**Comment by timsawtell-sportsbet** [comment]
Hi @mehdijjz,

The latest version of this library now supports `fontSize` and `fontFamily` options for both `Group` and `Item` components. Hope this helps :)
