### ISSUE TITLE
there are no selector lines in picker when onChange prop is passed

### ISSUE THREAD

**Issue by Boris-Vladimirovich** [sportsbet/react-native-ultra-picker-ios#4]
I`m trying to use your picker in empty project, but the result is like this:
![simulator screen shot 27 2017 20 19 34](https://user-images.githubusercontent.com/12661419/30927504-57ff4560-a3c1-11e7-8782-c926f63aeb2b.png)
There is no  horizon selector lines. I've found that it happens when onChange prop is passed to UltraPickerIOS. How can I fix it? Maybe I did something wrong? Thanks in advance.

**Comment by timsawtell-sportsbet** [comment]
Try upgrading to version 1.5

**Comment by timsawtell-sportsbet** [comment]
Sorry, 1.5 was a bad release, I quickly made a 0.1.6
